plugin:
    name: 'frukt.frushop::lang.plugin.name'
    description: 'frukt.frushop::lang.plugin.description'
    author: Frukt
    icon: oc-icon-shopping-cart
    homepage: ''
navigation:
    main-menu-item:
        label: FRUSHOP
        url: /
        icon: icon-shopping-cart
        sideMenu:
            side-menu-item:
                label: Категории
                url: frukt/frushop/categories
                icon: icon-sitemap
            side-menu-item2:
                label: Продукты
                url: frukt/frushop/products
                icon: icon-tablet
