list: $/frukt/frushop/models/product/columns.yaml
modelClass: Frukt\Frushop\Models\Product
title: Products
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'frukt/frushop/products/update/:id'
filter: config_filter.yaml
